Sort by popularity and add badges
vinegarhq/vinegarhq.github.io pull request #103
Opened 2023-12-04 22:50 UTC by tacheometry

2023-12-04 22:59 UTC, Noted-Jrelvas commented
Ooo, I like this. Only note I have is that listing snap along with normal system packaging feels a bit... weird. Maybe we should put on a separate section? Either way, just a minor nitpick. Could you give me your thoughts on that please?

2023-12-04 23:00 UTC, tacheometry commented
Sure, I'll move it to another section

2023-12-04 23:16 UTC, Noted-Jrelvas approved these changes

2023-12-05 11:50 UTC, apprehensions requested changes

2023-12-05 11:50 UTC, apprehensions commented on src/Installation/guides/package.md
> +apk add vinegar
```suggestion
Vinegar's Alpine package resides within the [Edge testing repository](https://wiki.alpinelinux.org/wiki/Repositories#Edge), see more on how to set it up [here](https://wiki.alpinelinux.org/wiki/Repositories#Managing_repositories)
```sh
# apk add vinegar
```

2023-12-05 11:50 UTC, apprehensions commented on src/Installation/guides/package.md
> +dnf install vinegar
```suggestion
```sh
# dnf copr enable thegu5/vinegar
# dnf install vinegar
```

2023-12-05 13:00 UTC, merged