Make clearer to not use channel option and adding 403 error to troubleshooting.
vinegarhq/vinegarhq.github.io pull request #114
Opened 2024-01-10 22:30 UTC by Cristiandis

2024-01-10 22:35 UTC, Noted-Jrelvas requested changes

2024-01-10 22:35 UTC, Noted-Jrelvas commented on src/Configuration/index.md
> +| ~~`channel`~~          | the deployment channel to be used; **DO NOT CHANGE, ONLY KEPT FOR DEVELOPERS**                   | `"LIVE"`           |
I feel like this change is unnecessary.

2024-01-10 22:35 UTC, Noted-Jrelvas commented on src/Troubleshooting/index.md
> +
I dislike the way this is worded. Feels like a word salad.

2024-01-10 23:05 UTC, Noted-Jrelvas commented on src/Troubleshooting/index.md
> +This is caused by Roblox locking all channels except `live`, this can be easily fixed by removing the `channel` option.
```suggestion
On Oct. 2023, [Roblox decided to restrict access to all channels](https://devforum.roblox.com/t/-/2487241/7). If the `channel` option is set to anything other than `live`, you will run into this issue. This option should be removed from your configuration.
```
Hmm...

2024-01-10 23:35 UTC, lunarlettuce commented
That's not true, having the channel selector set to anything at all will cause a 403.

2024-01-11 00:58 UTC, Noted-Jrelvas commented
Excellent. Less words needed in docs then.

2024-01-11 01:00 UTC, Noted-Jrelvas commented on src/Troubleshooting/index.md
> +This is caused by Roblox locking all channels except `live`, this can be easily fixed by removing the `channel` option.
```suggestion
On Oct. 2023, [Roblox decided to restrict access to all channels](https://devforum.roblox.com/t/-/2487241/7). If the `channel` option is set, you will run into this issue. It should be removed from your configuration.
```

2024-01-11 04:35 UTC, closed without merging