Add studio backup section
vinegarhq/vinegarhq.github.io pull request #123
Opened 2024-03-06 07:17 UTC by Eggflaw

Related to issue [#406](https://github.com/vinegarhq/vinegar/issues/406).

2024-03-06 14:46 UTC, jrelvas-ipc commented on src/Configuration/tips-and-tricks/index.md
> +Before you delete your wineprefixes via `vinegar delete` or `flatpak run org.vinegarhq.Vinegar delete`, you should backup data you have on your Studio prefix. This includes your settings, files you h
@apprehensions Is Studio saving local files on the prefix? We might want to change that.

--

In this case, I don't think the `etc.` is needed as there's actually no other kinds of data, so I'd word it more like:
```suggestion
Before you delete your wineprefixes via `vinegar delete` or `flatpak run org.vinegarhq.Vinegar delete`, you should backup data you have on your Studio prefix. This includes your settings and files you've stored.
```

2024-03-06 14:48 UTC, jrelvas-ipc commented on src/Configuration/tips-and-tricks/index.md
> +- `(studio prefix)/drive_c/users/(username)/AppData/Local/Roblox/GlobalBasicSettings_13_Studio.xml`: MicroProfiler, Fullscreen etc
Some fixes to text consistency needed:
```suggestion
- `(studio prefix)/user.reg`: Studio theme, Docking layout.
- `(studio prefix)/drive_c/users/(username)/AppData/Local/Roblox/GlobalSettings_13.xml`: Display language, Fonts, etc. 
- `(studio prefix)/drive_c/users/(username)/AppData/Local/Roblox/GlobalBasicSettings_13_Studio.xml`: MicroProfiler, Fullscreen, etc.
```

2024-03-06 14:49 UTC, jrelvas-ipc requested changes
See earlier comments.

2024-03-07 00:18 UTC, Eggflaw reviewed
Fixed.

2024-03-20 16:08 UTC, jrelvas-ipc approved these changes
All looks fine to me!

2024-03-20 16:09 UTC, merged