Updating Troubleshooting.md
vinegarhq/vinegarhq.github.io pull request #126
Opened 2024-07-01 05:50 UTC by tristann21

Added "Wine is not supported" error message in the troubleshooting page. 

Thanks for showing me how to contribute to open source!

2024-07-01 05:56 UTC, apprehensions requested changes

2024-07-01 06:53 UTC, apprehensions commented
unhelpful commit messages

2024-07-01 06:56 UTC, tristann21 commented
> unhelpful commit messages

Oh whoops sorry I was just clicking "approve" or whatever github was telling me to do, I'll make the titles more clear next time. Thanks!

2024-07-03 22:25 UTC, apprehensions requested changes

2024-07-03 22:25 UTC, apprehensions commented on src/Troubleshooting/index.md
> +Workarounds such as running Roblox in a virtual machine or Android emulation with Waydroid is still possible; read the pinned thread in the helpdesk channel present in the VinegarHQ discord server fo
```suggestion
Workarounds such as running Roblox in a virtual machine or Android emulation with Waydroid are still possible; read the pinned thread in the helpdesk channel present in the VinegarHQ discord server for more information.
```

2024-07-03 22:26 UTC, merged