Now, Vinegar has a GUI.
vinegarhq/vinegarhq.github.io pull request #77
Opened 2023-10-12 18:05 UTC by BlueTree242

2023-10-12 18:29 UTC, Cristiandis commented
No, its just a loading screen
Gui in terms of config there's none

2023-10-12 19:14 UTC, Noted-Jrelvas commented
According to @BlueTree242's patch, this is a Graphical User Interface.

![imagem](https://github.com/vinegarhq/vinegarhq.github.io/assets/55360900/f8eec77a-6a9a-4c1e-96d7-e90c23089dd7)

2023-10-12 19:37 UTC, Cristiandis commented
> According to @BlueTree242's patch, this is a Graphical User Interface.
> 
> ![imagem](https://user-images.githubusercontent.com/55360900/274708386-f8eec77a-6a9a-4c1e-96d7-e90c23089dd7.png)

Real

2023-10-12 19:37 UTC, Cristiandis commented
Close this pr

2023-10-12 19:38 UTC, apprehensions commented
No

2023-10-12 20:57 UTC, tacheometry requested changes

2023-10-12 20:57 UTC, tacheometry commented on src/Home/index.md
> +- There is no <abbr title="Graphical User Interface">GUI</abbr> for Vinegar at this time, but there's a loading screen.
```suggestion
- There is no graphical configuration interface for Vinegar at this time.
```

2023-10-13 22:02 UTC, tacheometry approved these changes

2023-10-14 17:18 UTC, merged